name: "Auto Build"

on:
  push:
    branches:
      - "main"
    paths:
      - "app/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
      - "!**/.gitignore"
      - "!app/src/*[Tt]est/**"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create keystore files
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -di > release.keystore
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties

      - name: Build
        id: build
        run: ./gradlew assemble

      - name: GH Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.build.outcome == 'success' }}
        with:
          name: "Auto build"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: true
          body: |
            Use at your own risk!
            These builds may be broken and some changes may lose settings or require clearing app data.
            If you have a final release installed and want to preserve its settings while testing this, you can install the debug build alongside it.
          generate_release_notes: true
          files: 'app/build/outputs/apk/**/*.apk'
